name = "gamesearch-api"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# Add any environment variables here if needed

# For local development, you can also add:
# [env.dev.vars]
# DEBUG = "true"